name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Package
      run: upx --best --lzma ./target/release/mith
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Mith
        path: target/release/mith
